# Generated by Django 3.2.7 on 2021-09-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questiongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.BooleanField()),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('GEO', 'Geo'), ('FREE', 'Free'), ('NUMERIC', 'Numeric'), ('OPTION', 'Option'), ('PHOTO', 'Photo'), ('DATE', 'Date')], default='FREE', max_length=8)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questiongroup')),
            ],
        ),
    ]
