# Generated by Django 3.2.7 on 2021-09-20 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_name',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('WOREDA', 'Woreda'), ('KEBELE', 'Kebele')], default='WOREDA', max_length=6)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.administration')),
            ],
        ),
    ]
