	git checkout main README.md
	git checkout main backend/.gitignore
	git checkout main backend/alembic/env.py
	git checkout main backend/alembic/versions/2023-04-23-23-43-05_7402b7f0738c_add_long_name_to_administration.py
	git checkout main backend/core/config.py
	git checkout main backend/db/connection.py
	git checkout main backend/db/crud_question_group.py
	git checkout main backend/dev.sh
	git checkout main backend/models/administration.py
	git checkout main backend/models/jobs.py
	git checkout main backend/routes/jobs.py
	git checkout main backend/seeder/cleandb.py
	git checkout main backend/seeder/organisation.py
	git checkout main backend/seeder/update_options.py
	git checkout main backend/source/generate_id.py
	git checkout main backend/source/notset/data/cascade.csv
	git checkout main backend/source/wai-bangladesh/category.json
	git checkout main backend/source/wai-bangladesh/config.js
	git checkout main backend/source/wai-bangladesh/data/cascade.csv
	git checkout main backend/source/wai-bangladesh/forms/557760069.json
	git checkout main backend/source/wai-bangladesh/forms/563280066.json
	git checkout main backend/source/wai-bangladesh/forms/574850091.json
	git checkout main backend/source/wai-demo/form_url_dump.json
	git checkout main backend/source/wai-demo/forms/494780323.json
	git checkout main backend/source/wai-demo/forms/551870264.json
	git checkout main backend/source/wai-demo/forms/567420165.json
	git checkout main backend/source/wai-demo/forms/567420197.json
	git checkout main backend/source/wai-demo/forms/571070071.json
	git checkout main backend/source/wai-ethiopia/category.json
	git checkout main backend/source/wai-ethiopia/config.js
	git checkout main backend/source/wai-ethiopia/forms/494780323.json
	git checkout main backend/source/wai-ethiopia/forms/551870264.json
	git checkout main backend/source/wai-ethiopia/forms/567420165.json
	git checkout main backend/source/wai-ethiopia/forms/567420197.json
	git checkout main backend/source/wai-ethiopia/forms/571070071.json
	git checkout main backend/source/wai-nepal/config.js
	git checkout main backend/source/wai-nepal/forms/1323574110.json
	git checkout main backend/source/wai-nepal/forms/554360198.json
	git checkout main backend/source/wai-nepal/forms/556240162.json
	git checkout main backend/source/wai-nepal/forms/557950127.json
	git checkout main backend/source/wai-nepal/forms/child-1260775092.json
	git checkout main backend/source/wai-nepal/forms/child-1322834054.json
	git checkout main backend/source/wai-nepal/forms/child-1327205184.json
	git checkout main backend/source/wai-nepal/forms/child-1338414049.json
	git checkout main backend/source/wai-uganda/category.json
	git checkout main backend/source/wai-uganda/config.js
	git checkout main backend/source/wai-uganda/forms/01.json
	git checkout main backend/source/wai-uganda/forms/02.json
	git checkout main backend/source/wai-uganda/forms/03.json
	git checkout main backend/source/wai-uganda/forms/04.json
	git checkout main backend/tests/test_11_jobs.py
	git checkout main backend/tests/test_13_worker_service.py
	git checkout main backend/worker.py
	git checkout main ci/build.sh
	git checkout main ci/deploy.sh
	git checkout main ci/k8s/deployment.yml.template
	git checkout main ci/test/basic.sh
	git checkout main ci/test/entrypoint.sh
	git checkout main db/docker-entrypoint-initdb.d.ci/000-init.sql
	git checkout main db/docker-entrypoint-initdb.d/000-init.sql
	git checkout main db/docker-entrypoint-initdb.d/wai-ethiopia/000-init.sql.sh
	git checkout main db/script/dump-db.sh
	git checkout main deploy/backup_data.sh
	git checkout main deploy/docker-compose.yml
	git checkout main deploy/install.sh
	git checkout main docker-compose.ci.yml
	git checkout main docker-compose.test.yml
	git checkout main docs/wai-bangladesh/assets/ethiopia/adavanced-filter-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/add-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/advanced-filter.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/bar-chart.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/data-entry-upload.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/dataset-overview.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/datasets.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/delete-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/edit-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/example-overview.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/export-filter.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/filter-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/filter.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/jmp-chart.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/legend.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/list-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/list-of-exported-data-entry.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/login.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/manage-users.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/map.png
	git checkout main docs/wai-bangladesh/assets/ethiopia/table-view.png
	git checkout main docs/wai-bangladesh/source/ethiopia/admin.rst
	git checkout main docs/wai-bangladesh/source/ethiopia/data.rst
	git checkout main docs/wai-bangladesh/source/ethiopia/datasets.rst
	git checkout main docs/wai-bangladesh/source/ethiopia/gettingStarted.rst
	git checkout main docs/wai-demo/assets/adavanced-filter-data-entry.png
	git checkout main docs/wai-demo/assets/add-data-entry.png
	git checkout main docs/wai-demo/assets/advanced-filter.png
	git checkout main docs/wai-demo/assets/bar-chart.png
	git checkout main docs/wai-demo/assets/data-entry-upload.png
	git checkout main docs/wai-demo/assets/dataset-overview.png
	git checkout main docs/wai-demo/assets/datasets.png
	git checkout main docs/wai-demo/assets/delete-data-entry.png
	git checkout main docs/wai-demo/assets/edit-data-entry.png
	git checkout main docs/wai-demo/assets/example-overview.png
	git checkout main docs/wai-demo/assets/export-filter.png
	git checkout main docs/wai-demo/assets/filter-data-entry.png
	git checkout main docs/wai-demo/assets/filter.png
	git checkout main docs/wai-demo/assets/jmp-chart.png
	git checkout main docs/wai-demo/assets/legend.png
	git checkout main docs/wai-demo/assets/list-data-entry.png
	git checkout main docs/wai-demo/assets/list-of-exported-data-entry.png
	git checkout main docs/wai-demo/assets/login.png
	git checkout main docs/wai-demo/assets/manage-users.png
	git checkout main docs/wai-demo/assets/map.png
	git checkout main docs/wai-demo/assets/table-view.png
	git checkout main docs/wai-ethiopia/assets/adavanced-filter-data-entry.png
	git checkout main docs/wai-ethiopia/assets/add-data-entry.png
	git checkout main docs/wai-ethiopia/assets/advanced-filter.png
	git checkout main docs/wai-ethiopia/assets/bar-chart.png
	git checkout main docs/wai-ethiopia/assets/data-entry-upload.png
	git checkout main docs/wai-ethiopia/assets/dataset-overview.png
	git checkout main docs/wai-ethiopia/assets/datasets.png
	git checkout main docs/wai-ethiopia/assets/delete-data-entry.png
	git checkout main docs/wai-ethiopia/assets/edit-data-entry.png
	git checkout main docs/wai-ethiopia/assets/example-overview.png
	git checkout main docs/wai-ethiopia/assets/export-filter.png
	git checkout main docs/wai-ethiopia/assets/filter-data-entry.png
	git checkout main docs/wai-ethiopia/assets/filter.png
	git checkout main docs/wai-ethiopia/assets/jmp-chart.png
	git checkout main docs/wai-ethiopia/assets/legend.png
	git checkout main docs/wai-ethiopia/assets/list-data-entry.png
	git checkout main docs/wai-ethiopia/assets/list-of-exported-data-entry.png
	git checkout main docs/wai-ethiopia/assets/login.png
	git checkout main docs/wai-ethiopia/assets/manage-users.png
	git checkout main docs/wai-ethiopia/assets/map.png
	git checkout main docs/wai-ethiopia/assets/table-view.png
	git checkout main docs/wai-nepal/assets/ethiopia/adavanced-filter-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/add-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/advanced-filter.png
	git checkout main docs/wai-nepal/assets/ethiopia/bar-chart.png
	git checkout main docs/wai-nepal/assets/ethiopia/data-entry-upload.png
	git checkout main docs/wai-nepal/assets/ethiopia/dataset-overview.png
	git checkout main docs/wai-nepal/assets/ethiopia/datasets.png
	git checkout main docs/wai-nepal/assets/ethiopia/delete-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/edit-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/example-overview.png
	git checkout main docs/wai-nepal/assets/ethiopia/export-filter.png
	git checkout main docs/wai-nepal/assets/ethiopia/filter-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/filter.png
	git checkout main docs/wai-nepal/assets/ethiopia/jmp-chart.png
	git checkout main docs/wai-nepal/assets/ethiopia/legend.png
	git checkout main docs/wai-nepal/assets/ethiopia/list-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/list-of-exported-data-entry.png
	git checkout main docs/wai-nepal/assets/ethiopia/login.png
	git checkout main docs/wai-nepal/assets/ethiopia/manage-users.png
	git checkout main docs/wai-nepal/assets/ethiopia/map.png
	git checkout main docs/wai-nepal/assets/ethiopia/table-view.png
	git checkout main docs/wai-nepal/source/ethiopia/admin.rst
	git checkout main docs/wai-nepal/source/ethiopia/data.rst
	git checkout main docs/wai-nepal/source/ethiopia/datasets.rst
	git checkout main docs/wai-nepal/source/ethiopia/gettingStarted.rst
	git checkout main docs/wai-uganda/assets/ethiopia/adavanced-filter-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/add-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/advanced-filter.png
	git checkout main docs/wai-uganda/assets/ethiopia/bar-chart.png
	git checkout main docs/wai-uganda/assets/ethiopia/data-entry-upload.png
	git checkout main docs/wai-uganda/assets/ethiopia/dataset-overview.png
	git checkout main docs/wai-uganda/assets/ethiopia/datasets.png
	git checkout main docs/wai-uganda/assets/ethiopia/delete-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/edit-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/example-overview.png
	git checkout main docs/wai-uganda/assets/ethiopia/export-filter.png
	git checkout main docs/wai-uganda/assets/ethiopia/filter-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/filter.png
	git checkout main docs/wai-uganda/assets/ethiopia/jmp-chart.png
	git checkout main docs/wai-uganda/assets/ethiopia/legend.png
	git checkout main docs/wai-uganda/assets/ethiopia/list-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/list-of-exported-data-entry.png
	git checkout main docs/wai-uganda/assets/ethiopia/login.png
	git checkout main docs/wai-uganda/assets/ethiopia/manage-users.png
	git checkout main docs/wai-uganda/assets/ethiopia/map.png
	git checkout main docs/wai-uganda/assets/ethiopia/table-view.png
	git checkout main docs/wai-uganda/source/ethiopia/admin.rst
	git checkout main docs/wai-uganda/source/ethiopia/data.rst
	git checkout main docs/wai-uganda/source/ethiopia/datasets.rst
	git checkout main docs/wai-uganda/source/ethiopia/gettingStarted.rst
	git checkout main frontend/src/components/LoadMoreButton.jsx
	git checkout main frontend/src/components/PaginationApi.jsx
	git checkout main frontend/src/config.js
	git checkout main frontend/src/pages/admin/ManageUpload.jsx
	git checkout main frontend/src/pages/main/MainMaps.jsx
	git checkout main frontend/src/pages/main/main.scss
	git checkout main frontend/src/pages/main/tabs/TabJMP.jsx
	git checkout main frontend/src/pages/main/tabs/index.js
	git checkout main frontend/src/setupTests.js
	git checkout main frontend/src/state/ui.js
	git checkout main frontend/src/util/endpoints.js
	git checkout main frontend/src/util/utils.js
