import enum


class Corrections(enum.Enum):
    wai_ethiopia = {
        "Negele Arsi": "Negelle Arsi",
        "Shahamene": "Shahemene",
        "Jigessa Korke": "Jegesa Korke",
        "Jigesa qorke": "Jegesa Korke",
        "Kersa Maja": "Kersa Meja",
        "Bute Filicha": "Bute Felicha",
        "Turufe Watara elemo": "Turre Wetera Elemo",
        "Mararo": "Meraro",
        "Hursa Simbo": "Hursa Sinbo",
        "Jalo Dida": "Jelo Dida",
        "Aradano Shifa": "Aredano Shifa",
        "Kubi Guta": "Kubi guta",
        "Oine Cafo umbure": "Oine Chefo Unbule",
        "Bulchana Danaba": "Bulchana Deneba",
        "Bura Borama": "Bura Borema",
        "Obenso Jalo": "Obenso Jilo",
        "Cabi Dida": "Jelo Dida",
        "Cabi Dida nyataa": "Jelo Dida",
        "Gonde Qarso": "Gonde Kerso",
        "Maja Dama": "Meja Dema",
        "Faji Goba": "Faji Gole",
        "Wayo Danisa": "Danisa",
        "Turge Galo": "Terge Galo",
        "Kersa Gara": "Kersa Gera",
        "Karara Filicha": "kerara Felicha",
        "Ali": "Ali Wayo",
        "Alge lak 2": "Alge",
        "Bila": "Shala Bila",
        "Bulchana Danaba": "Bulchana Deneba",
        "Culule Habara": "Chulule Habera",
        "Arjo": "Gebta Arjo",
        "Kore Rogicha": "Korerogicha",
        "Abaroo": "Abaro",
        "Gorbi Arba": "Gerbi Arba",
        "Edo Jigessa": "Edo Jigessa",
        "Hagugata quni": "Hagugeta Keni",
        "Kore Borojota": "Kori Borejeta",
        "ilala Qorke": "Ilalal Korke",
        "Jangala Wandare": "Jengele Wendere",
        "Alelu ilu": "Ale Luilu",
        "Wayo Danisa": "Danisa",
        "Chafa Gutaa": "Chefageta",
        "Edola Burqa": "Ido Laburka",
        "Watara Shagule": "Wetera Shegule",
        "Wotara Shagule": "Wetera Shegule",
        "Xaxesa dadesa": "Tatesa Dedesa"
    }
    wai_bangladesh = {}
    wai_uganda = {}
